artifact_location: file:///c:/Users/maria/OneDrive - Universidad de los Andes/Universidad/Octavo
  Semestre/Analitica/Modelos-predictivos-Atlantico/Tarea 4 - Modelamiento/mlruns_modelreg/258742023502006537
creation_time: 1779730195515
experiment_id: '258742023502006537'
last_update_time: 1779730195515
lifecycle_stage: active
name: saber11_regresion_atlantico
trace_location: null
workspace: default
