artifact_uri: file:///c:/Users/maria/OneDrive - Universidad de los Andes/Universidad/Octavo
  Semestre/Analitica/Modelos-predictivos-Atlantico/Tarea 4 - Modelamiento/mlruns_modelreg/258742023502006537/ccb641eb98d04998a767bc1eaeb1f46b/artifacts
end_time: 1779730542982
entry_point_name: ''
experiment_id: '258742023502006537'
lifecycle_stage: active
run_id: ccb641eb98d04998a767bc1eaeb1f46b
run_name: capable-auk-759
source_name: ''
source_type: 4
source_version: ''
start_time: 1779730195557
status: 3
tags: []
user_id: maria
