artifact_location: file:///c:/Users/maria/OneDrive - Universidad de los Andes/Universidad/Octavo
  Semestre/Analitica/Modelos-predictivos-Atlantico/Tarea 4 - Modelamiento/mlruns_modelreg/258742023502006537/models/m-0b373c16bfb2419a97ef88bf987b9db4/artifacts
creation_timestamp: 1779730195762
experiment_id: '258742023502006537'
last_updated_timestamp: 1779730529475
model_id: m-0b373c16bfb2419a97ef88bf987b9db4
model_type: null
name: model
source_run_id: ccb641eb98d04998a767bc1eaeb1f46b
status: 2
status_message: null
