artifact_location: file:///c:/Users/maria/OneDrive - Universidad de los Andes/Universidad/Octavo
  Semestre/Analitica/Modelos-predictivos-Atlantico/Tarea 4 - Modelamiento/mlruns_modelreg/0
creation_time: 1779730195487
experiment_id: '0'
last_update_time: 1779730195487
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
